apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
  labels:
    app: kafka
spec:
  replicas: 3
  image:
    application: confluentinc/cp-server-operator:6.1.0.0
    init: confluentinc/cp-init-container-operator:6.1.0.0
  storageClass:
    name: standard
  dataVolumeCapacity: 50Gi
  listeners:
    external:
      externalAccess:
        type: nodePort
        tls: true
          authentication:
            type: tls
          overrides:
            bootstrap:
              nodePort: 30001
            brokers:
              - broker: 0
                nodePort: 30002
              - broker: 1
                nodePort: 30003
              - broker: 2
                nodePort: 30004
    #    nodePort:
   #       host: kafka.iris-streaming-sb.devtest.aws.scania.com
  #        nodePortOffset: 30000
#        loadBalancer:
#          annotations:
#            service.beta.kubernetes.io/aws-load-balancer-type: nlb
#            service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
#            service.beta.kubernetes.io/aws-load-balancer-name: iris-streaming-sb-kafka-nlb
#            service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-0e18497ffe09aa1bc, subnet-0869429a688c9e4ad, subnet-0a3762c0ef8a83cf0
#            service.beta.kubernetes.io/load-balancer-source-ranges: 13.51.132.182/32, 13.51.115.193/32, 13.51.138.3/32
#            service.beta.kubernetes.io/aws-load-balancer-scheme: internal
#
#          domain: iris-streaming-sb.devtest.aws.scania.com
#          bootstrapPrefix: kafka
#          brokerPrefix: s
  metricReporter:
    enabled: true
  oneReplicaPerNode: true
  podTemplate:
    podSecurityContext:
      fsGroup: 1000
      runAsGroup: 1000
      runAsUser: 1000
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: service
                  operator: In
                  values:
                    - kafka0
                    - kafka1
                    - kafka2
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: service
                  operator: In
                  values:
                    - zookeeper
                    - confluent
                    - controlcenter
            topologyKey: kubernetes.io/hostname
