kind: Service
apiVersion: v1
metadata:
  name: kafka
  annotations:
            service.beta.kubernetes.io/aws-load-balancer-type: nlb
            service.beta.kubernetes.io/aws-load-balancer-scheme: internal
spec:
  selector:
    service: kafka0
  type: LoadBalancer
  ports:
    - name: kafka0
      port: 80
      targetPort: 9092
      protocol: TCP
