kind: Service
apiVersion: v1
metadata:
  name: kafka
  labels:
    app: kafka
    statefulset.kubernetes.io/pod-name: kafka-2
  annotations:
            service.beta.kubernetes.io/aws-load-balancer-name: iris-streaming-sb-kafka-nlb
            service.beta.kubernetes.io/aws-load-balancer-type: nlb
            service.beta.kubernetes.io/aws-load-balancer-scheme: internal
            service.beta.kubernetes.io/aws-load-balancer-hostname: iris-streaming-sb.devtest.aws.scania.com
spec:
  type: LoadBalancer
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
      protocol: TCP
