apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: iris-streaming-sb.devtest.aws.scania.com
    external-dns.alpha.kubernetes.io/ttl: "300"
    platform.confluent.io/cr-name: kafka
    platform.confluent.io/namespace: confluent
    platform.confluent.io/type: kafka
  labels:
    app.kubernetes.io/managed-by: confluent-operator
    confluent-platform: "true"
    cr-name: kafka
    type: kafka
  name: kafka-0-np
  namespace: confluent
  ownerReferences:
    - apiVersion: platform.confluent.io/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: Kafka
      name: kafka
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: external
      port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    app: kafka
    clusterId: confluent
    confluent-platform: "true"
    statefulset.kubernetes.io/pod-name: kafka-0
    type: kafka
  sessionAffinity: None
  type: NodePort