installCRDs: true
webhook:
  securePort: 9999
  hostNetwork: true
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::858242954753:role/cert-manager-irsa
securityContext:
  fsGroup: 1001
