apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-monitor
  namespace: confluent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-monitor
  template:
    metadata:
      labels:
        app: kafka-monitor
    spec:
      containers:
      - name: kafka-monitor
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "50m"
        env:
        - name: DATADOG_API_KEY
          valueFrom:
            secretKeyRef:
              name: kafka-monitor-secret
              key: DATADOG_API_KEY
        - name: SERVICE_USERNAME
          valueFrom:
            secretKeyRef:
              name: kafka-monitor-secret
              key: SERVICE_USERNAME
        - name: SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-monitor-secret
              key: SERVICE_PASSWORD
        - name: SERVICE_URLS
          valueFrom:
            configMapKeyRef:
              name: kafka-monitor-config
              key: SERVICE_URLS
        - name: TELNET_HOSTS_PORTS
          valueFrom:
            configMapKeyRef:
              name: kafka-monitor-config
              key: TELNET_HOSTS_PORTS
        - name: HOST
          value: {{ .Values.host }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-monitor-config
  namespace: confluent
data:
  SERVICE_URLS: {{ .Values.SERVICE_URLS }}
  TELNET_HOSTS_PORTS: {{ .Values.TELNET_HOSTS_PORTS }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kafka-monitor-secret
  namespace: confluent
spec:
  refreshInterval: "1m"  # May be set to zero to fetch and create it once
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  target:
    name: kafka-monitor-secret
    creationPolicy: Owner
  data:
    - secretKey: SERVICE_USERNAME
      remoteRef:
        key: {{ .Values.KAFKA_MONITOR }}
        property: SERVICE_USERNAME
    - secretKey: SERVICE_PASSWORD
      remoteRef:
        key: {{ .Values.KAFKA_MONITOR }}
        property: SERVICE_PASSWORD
    - secretKey: DATADOG_API_KEY
      remoteRef:
        key: {{ .Values.KAFKA_MONITOR }}
        property: DATADOG_API_KEY
