##
## License Key for Operator
## TODO: use license.secretref to populate from license secret instead.
licenseKey: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjb250cm9sLWNlbnRlciIsIm5iNCI6IjE3MDEzNjQ2MzIiLCJtb25pdG9yaW5nIjp0cnVlLCJsaWNlbnNlVHlwZSI6IkVudGVycHJpc2UiLCJpc3MiOiJDb25mbHVlbnQiLCJpYXQiOjE2OTkwODEyMDAsImV4cCI6MTc0NTk5NjQwMCwiYXVkIjoiMDA2NFUwMDAwMHRyYU9NUUFZIn0=.AGjGsrGh9Nmu7jQGops_3QLWhCPD4TypKHOzyYlFt4HyyE4q6zeY1AgbfEMnj1kSgdaSIv7dmaRdw4jqVjwx5zAE9Nu7bhX8Pdhd_x7aTZp83iNkHTzu2Vf4CdlpACUcbBem9HnEPIyrMHwwdn83vmiXA5ZLGujsfhm_nQt6d7PnBgvrb3l3t8YC_5u2lPUdq4XfXxaq3tqWsgQYvufq-wuinayP8Q0s0kL5dWwnli9FBJXdW9uGCRWRARzDtmT66sH_nNv3n3Td8eBHitbEUWjGNjA4QnbjAuJssBjUh9zMC3X_iyv4XjK0BkExFjdg2SxEwQql7pd0bK2mfQzZVg"

replicas: 1
resources:
   limits:
     memory: 2Gi

clusterRole:
  openshift: false