##
## License Key for Operator
## TODO: use license.secretref to populate from license secret instead.
#licenseKey: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjb250cm9sLWNlbnRlciIsIm5iNCI6IjE3MDEzNjQ2MzIiLCJtb25pdG9yaW5nIjp0cnVlLCJsaWNlbnNlVHlwZSI6IkVudGVycHJpc2UiLCJpc3MiOiJDb25mbHVlbnQiLCJpYXQiOjE2OTkwODEyMDAsImV4cCI6MTc0NTk5NjQwMCwiYXVkIjoiMDA2NFUwMDAwMHRyYU9NUUFZIn0=.AGjGsrGh9Nmu7jQGops_3QLWhCPD4TypKHOzyYlFt4HyyE4q6zeY1AgbfEMnj1kSgdaSIv7dmaRdw4jqVjwx5zAE9Nu7bhX8Pdhd_x7aTZp83iNkHTzu2Vf4CdlpACUcbBem9HnEPIyrMHwwdn83vmiXA5ZLGujsfhm_nQt6d7PnBgvrb3l3t8YC_5u2lPUdq4XfXxaq3tqWsgQYvufq-wuinayP8Q0s0kL5dWwnli9FBJXdW9uGCRWRARzDtmT66sH_nNv3n3Td8eBHitbEUWjGNjA4QnbjAuJssBjUh9zMC3X_iyv4XjK0BkExFjdg2SxEwQql7pd0bK2mfQzZVg"
licenseKey: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjb250cm9sLWNlbnRlciIsIm5iNCI6IjE3NDM0MDQzNDUiLCJtb25pdG9yaW5nIjp0cnVlLCJsaWNlbnNlVHlwZSI6IkVudGVycHJpc2UiLCJpc3MiOiJDb25mbHVlbnQiLCJpYXQiOjE3NDM0MDQ0MDAsImV4cCI6MTc3NzUzMjQwMCwiYXVkIjoiMDA2NFUwMDAwMHVhNlg4UUFJIn0=.nq6o8qmUbGDUrfkvEKYXv_42RXLJPFQ9BEyCIcJYVeagBrt-VE0bTpMJe9ZRWEkV3BGMySFrLHm4yU0iuF-Gf9zAS2qrHGe1q1QTk4XTnsYiHu82L_RXPNNln1TRNmW30iaOZCe3ExW0WjfhYuFSylmPKsJRsLmmVcRSm8qccKUTinsTxdJSlSuCKXn9sRNLUW7TOxSEHx4XPOjvWb1TImAgquacljsZmENTeuyF9u994C4CaU-V3M65s5rmWYqYvVG3hdL0SHHoFdj738BWFZmxzruoj8QfbJ2O-lH9BFpBQI4-95vqVLxZBDz_fpLFOt5cUqTy3pdyxHjDlK2SHg"
replicas: 1
resources:
   limits:
     memory: 2Gi

clusterRole:
  openshift: false