environment: sandbox
clusterType: external

domain:
  name: iris-streaming-sb.devtest.aws.scania.com
  prefix:
    - mtlsaws
    - mtlsonprem
    - oauthaws
    - oauthonprem

externalSecret:
  enabled: false
  aws:
    roleArn: arn:aws:iam::572663323550:role/secrets_manager_sb_ext

ldapProxy:
  enabled: false

datadog:
  enabled: true
filebeat:
  enabled: true
kafkalagexporter:
  enabled: true

certManager:
  enabled: true
clusterIssuer:
  hostedZoneID: Z045221811UTX9KK3NEWU
