environment: sandbox
clusterType: internal

externalSecret:
  enabled: true
  aws:
    roleArn: arn:aws:iam::572663323550:role/secrets_manager_sb_int

ldapProxy:
  enabled: true

datadogAgent:
  enabled: false

datadog:
  enabled: true

filebeat:
  enabled: true
