environment: sandbox
clusterType: internal

domain:
  name: iris-streaming-sb.devtest.aws.scania.com
  prefix:
    - imtlsaws
    - imtlsonprem
    - ioauthaws
    - ioauthonprem

externalSecret:
  enabled: true
  aws:
    roleArn: arn:aws:iam::572663323550:role/secrets_manager_sb_int

ldapProxy:
  enabled: true

datadog:
  enabled: true
filebeat:
  enabled: true

certManager:
  enabled: false
clusterIssuer:
  hostedZoneID: Z045221811UTX9KK3NEWU