environment: production
clusterType: external
image: 858242954753.dkr.ecr.eu-north-1.amazonaws.com/kafka-monitor:1.25
SERVICE_URLS: "https://controlcenter.iris-streaming.devtest.aws.scania.com,https://schemaregistryaws.iris-streaming.devtest.aws.scania.com,https://restproxyaws.iris-streaming.devtest.aws.scania.com,https://ksqldbaws.iris-streaming.devtest.aws.scania.com,https://mds.kafka.iris-streaming.devtest.aws.scania.com/kafka/v3/clusters"
TELNET_HOSTS_PORTS: ""
