environment: sandbox
clusterType: internal

subnets:
  private: subnet-005c0a53190a785d7, subnet-000ec77e207799a57, subnet-0700aa03c92c90b8a
  #There are some public facing services, eg. control-center that needs this. Or should probably be fixed.
  public: subnet-05f7a5ed2f3bffe1f, subnet-01134504e0e2585cb, subnet-0b0d0d44264a719c2

domain: iris-streaming-sb.devtest.aws.scania.com

kerberos:
  activatedInKafka: false
  configuration: |
    [logging]
    default = FILE:/tmp/krb5libs.log
    kdc = FILE:/tmp/krb5kdc.log
    admin_server = FILE:/tmp/kadmind.log
    [libdefaults]
    dns_lookup_realm = false
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true
    rdns = false
    default_ccache_name = KEYRING:persistent:%{uid}
    verify_ap_req_nofail = false
    dns_canonicalize_hostname = false

    default_realm = GLOBAL.SCD.SCANIA.COM
    dns_lookup_kdc = false
    [realms]



    GLOBAL.SCD.SCANIA.COM = {
      kdc = selladc0001.global.scd.scania.com
    }



    [domain_realm]
    global.scd.scania.com = GLOBAL.SCD.SCANIA.COM
    .global.scd.scania.com = GLOBAL.SCD.SCANIA.COM
    
connect:
  instances:
    connect-onprem:
      replicas: 1
      image:
        application: confluentinc/cp-server-connect:7.1.1
      dns:
        prefix: ionpremconnect
      loadbalancer:
        ##TODO: is this really correct? Internal cluster connect has a external load-balancer.
        internal: true
        name: iris-streaming-sb-ionpremconnect
        nodeLabels: onpremconnect
      nodeAffinityServiceName: onpremconnect
      plugins:
      - name: kafka-connect-datagen
        owner: confluentinc
        version: 0.5.3
      - name: debezium-connector-mysql
        owner: debezium
        version: 1.8.1
      - name: kafka-connect-hdfs3
        owner: confluentinc
        version: 1.1.10
      configOverrides:
        server:
          'key.converter': 'org.apache.kafka.connect.storage.StringConverter'
          'value.converter': 'io.confluent.connect.avro.AvroConverter'
  
ksql:
  enabled: false

schemaRegistry:
  internalService:
    enabled: false
  loadbalancer:
    internal: true
    name: iris-streaming-sb-ischemaregistry
  replicas: 1
  dns:  
    prefix: ischemaregistry
  podAntiAffinity:
    - kafka
    - zookeeper
    - controlcenter

restProxy:
  authentication:
    type: mtls 
  dependencies:
    schemaRegistry: {}
  loadbalancer:
    internal: true
    name: iris-streaming-sb-irestproxy
  dns: 
    prefix: irestproxy
  podAntiAffinity:
  - kafka
  - zookeeper
  - controlcenter

zookeeper:
  dataVolumeCapacity: 40Gi
  logVolumeCapacity: 30Gi
  podAntiAffinity:
  - kafka
  - controlcenter
  - srrp

kafka:
  replicas: 3
  dataVolumeCapacity: 1500Gi
  oneReplicaPerNode: false
  authorization:
    superUsers:
    - User:kafka
    - User:servicesspadmintest  

  mountedSecrets:
  - secretRef: password-encoder-secret

  podAntiAffinity:
  - zookeeper
  - srrp
  - controlcenter

  configOverrides:
    server:
      'confluent.cluster.link.enable': 'true'
      'password.encoder.secret': '${file:/mnt/secrets/password-encoder-secret/password_encoder_secret:secret}'
      'confluent.balancer.enable': 'true'
      'confluent.balancer.heal.uneven.load.trigger': 'ANY_UNEVEN_LOAD'
      'ldap.com.sun.jndi.ldap.read.timeout': '60000'
      'ldap.refresh.interval.ms': '60000'
      'ldap.retry.timeout.ms': '6600000'
    jvm:
      '-Dcom.sun.jndi.ldap.debug': 'true'
      '-Djava.security.krb5.conf': '/etc/krb5.conf'

    log4j:
      'log4j.logger.io.confluent.security.auth.provider.ldap': 'TRACE'

  dependencies:
    kafkaRest:
      authentication:
        type: bearer
        bearer:
          secretRef: mds-client
  
  listeners: 
    internal: 
      enabled: true
    external: 
      enabled: true
      authentication:
        type: mtls
        principalMappingRules:
          # First rule may need to be altered to capture Scania-issued client certificates
          - RULE:.*Scania.*CN[ ]?=[ ]?([a-zA-Z0-9-_]+).*/$1/
          - RULE:.*CN[ ]?=[ ]?([a-zA-Z0-9-_]+).*\.scania\.com.*/$1/
      
      loadbalancer:
        bootstrapPrefix: imtlsonprem #TODO check if this is correct 
        brokerPrefix: imtlsonprem
        internal: true
        name: iris-streaming-sb-imtlsonprem-nlb
        sourceRanges: "13.48.228.240/32, 13.51.76.45/32, 13.51.129.156/32"
    custom: 
      internaleks:
        port: 9094
        loadbalancer:
          enabled: false
        authentication:
          type: mtls
          principalMappingRules:
            # First rule may need to be altered to capture Scania-issued client certificates
            - RULE:.*Scania.*CN[ ]?=[ ]?([a-zA-Z0-9-_]+).*/$1/
            - RULE:.*CN[ ]?=[ ]?([a-zA-Z0-9-_]+).*\.scania\.com.*/$1/
      ildaponprem:
        port: 9093
        authentication:
          type: ldap
        loadbalancer:
          enabled: true
          internal: true
          name: iris-streaming-sb-ildaponprem-nlb
          sourceRanges: "13.48.228.240/32, 13.51.76.45/32, 13.51.129.156/32"  


controlCenter:
  dataVolumeCapacity: 300Gi
  configOverrides:
    server:
      'confluent.controlcenter.mds.client.idle.timeout': '30000'
      'confluent.controlcenter.mds.client.max.requests.queued.per.destination': '2048'
  loadbalancer:
    name:  iris-streaming-sb-icontrolcenter
    nodeLabel: controlcenter
    certificateArn: arn:aws:acm:eu-north-1:572663323550:certificate/a29562a2-f4a3-4c03-b9b5-f77960e0580a
  nodeAffinityServiceName: controlcenter
  dns:
    prefix: icontrolcenter

