environment: sandbox
clusterType: internal

subnets:
  private: subnet-0eaa3d5224991d32b, subnet-03014a32c6f8a7d25, subnet-0416c0196a2569646
  #There are some public facing services, eg. control-center that needs this. Or should probably be fixed.
  public: subnet-05f7a5ed2f3bffe1f, subnet-01134504e0e2585cb, subnet-0b0d0d44264a719c2

domain: iris-streaming-sb.devtest.aws.scania.com

kerberos:
  activatedInKafka: false
  configuration: |
    [logging]
    default = FILE:/tmp/krb5libs.log
    kdc = FILE:/tmp/krb5kdc.log
    admin_server = FILE:/tmp/kadmind.log
    [libdefaults]
    dns_lookup_realm = false
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true
    rdns = false
    default_ccache_name = KEYRING:persistent:%{uid}
    verify_ap_req_nofail = false
    dns_canonicalize_hostname = false

    default_realm = GLOBAL.SCD.SCANIA.COM
    dns_lookup_kdc = false
    [realms]



    GLOBAL.SCD.SCANIA.COM = {
      kdc = selladc0001.global.scd.scania.com
    }



    [domain_realm]
    global.scd.scania.com = GLOBAL.SCD.SCANIA.COM
    .global.scd.scania.com = GLOBAL.SCD.SCANIA.COM
    
connect:
  instances:
    connect-onprem:
      cfkVersion: 2.5.1
      confluentVersion: 7.3.2
      replicas: 1
      dns:
        prefix: ionpremconnect
      loadbalancer:
        ##TODO: is this really correct? Internal cluster connect has a external load-balancer.
        internal: true
        name: iris-streaming-sb-ionpremconnect
        nodeLabels: onpremconnect
      nodeAffinityServiceName: onpremconnect
      plugins:
      - name: kafka-connect-datagen
        owner: confluentinc
        version: 0.5.3
      - name: debezium-connector-mysql
        owner: debezium
        version: 1.8.1
      - name: kafka-connect-hdfs3
        owner: confluentinc
        version: 1.1.10
      configOverrides:
        server:
          'key.converter': 'org.apache.kafka.connect.storage.StringConverter'
          'value.converter': 'io.confluent.connect.avro.AvroConverter'
        log4j:
          'log4j.appender.stdout': 'org.apache.log4j.ConsoleAppender'
          'log4j.appender.stdout.layout': 'org.apache.log4j.EnhancedPatternLayout'
          'log4j.appender.stdout.layout.ConversionPattern': '{"timestamp":"%d{ISO8601}","level":"%p","context":"%X{connector.context}","thread":"%t","class":"%C","message":"%m%throwable{full}"}%n'
          'log4j.appender.connectAppender.layout.ConversionPattern': '{"timestamp":"%d{ISO8601}","level":"%p","context":"%X{connector.context}","thread":"%t","class":"%C","message":"%m%throwable{full}"}%n'


schemaRegistry:
  cfkVersion: 2.5.1
  confluentVersion: 7.3.2
  internalService:
    enabled: false
  loadbalancer:
    internal: true
    name: iris-streaming-sb-ischemaregistry
  replicas: 1
  dns:  
    prefix: ischemaregistry
  podAntiAffinity:
    - kafka
    - zookeeper
    - controlcenter
  configOverrides:
    log4j:
      'log4j.appender.stdout': 'org.apache.log4j.ConsoleAppender'
      'log4j.appender.stdout.layout': 'org.apache.log4j.EnhancedPatternLayout'
      'log4j.appender.stdout.layout.ConversionPattern': '{"timestamp":"%d{ISO8601}","level":"%p","thread":"%t","class":"%C","message":"%m%throwable{full}"}%n'
    server:
      'confluent.schema.registry.anonymous.principal': 'true'
      'authentication.skip.paths': '/*'

restProxy:
  cfkVersion: 2.5.1
  confluentVersion: 7.3.2
  authentication:
    type: mtls 
  dependencies:
    schemaRegistry: {}
  loadbalancer:
    internal: true
    name: iris-streaming-sb-irestproxy
  dns: 
    prefix: irestproxy
  podAntiAffinity:
  - kafka
  - zookeeper
  - controlcenter
  configOverrides:
    log4j:
      'log4j.appender.stdout': 'org.apache.log4j.ConsoleAppender'
      'log4j.appender.stdout.layout': 'org.apache.log4j.EnhancedPatternLayout'
      'log4j.appender.stdout.layout.ConversionPattern': '{"timestamp":"%d{ISO8601}","level":"%p","thread":"%t","class":"%C","message":"%m%throwable{full}"}%n'

zookeeper:
  cfkVersion: 2.5.1
  confluentVersion: 7.3.2
  dataVolumeCapacity: 40Gi
  logVolumeCapacity: 30Gi
  podAntiAffinity:
  - kafka
  - controlcenter
  - srrp
  configOverrides:
    log4j:
      'log4j.logger.io.confluent.security.auth.provider.ldap': 'TRACE'
      'log4j.appender.stdout': 'org.apache.log4j.ConsoleAppender'
      'log4j.appender.stdout.layout': 'org.apache.log4j.EnhancedPatternLayout'
      'log4j.appender.stdout.layout.ConversionPattern': '{"timestamp":"%d{ISO8601}","level":"%p","thread":"%t","class":"%C","message":"%m%throwable{full}"}%n'

kafka:
  cfkVersion: 2.5.1
  confluentVersion: 7.3.2
  replicas: 3
  dataVolumeCapacity: 1500Gi
  oneReplicaPerNode: false
  authorization:
    superUsers:
    - User:serviceirisssptest  

  podAntiAffinity:
  - zookeeper
  - srrp
  - controlcenter

  configOverrides:
    server:
      'confluent.cluster.link.enable': 'true'
      'confluent.balancer.enable': 'true'
      'confluent.balancer.heal.uneven.load.trigger': 'ANY_UNEVEN_LOAD'
      'ldap.com.sun.jndi.ldap.read.timeout': '60000'
      'ldap.refresh.interval.ms': '60000'
      'ldap.retry.timeout.ms': '6600000'
      'connections.max.reauth.ms': '3600000'
    jvm:
      '-Dcom.sun.jndi.ldap.debug': 'true'
      '-Djava.security.krb5.conf': '/etc/krb5.conf'

    log4j:
      'log4j.logger.io.confluent.security.auth.provider.ldap': 'TRACE'
      'log4j.appender.stdout': 'org.apache.log4j.ConsoleAppender'
      'log4j.appender.stdout.layout': 'org.apache.log4j.EnhancedPatternLayout'
      'log4j.appender.stdout.layout.ConversionPattern': '{"timestamp":"%d{ISO8601}","level":"%p","thread":"%t","class":"%C","message":"%m%throwable{full}"}%n'

  dependencies:
    kafkaRest:
      authentication:
        type: bearer
        bearer:
          secretRef: mds-client
  
  listeners: 
    internal: 
      enabled: true
    external: 
      enabled: true
      authentication:
        type: mtls
        principalMappingRules:
          # First rule may need to be altered to capture Scania-issued client certificates
          - RULE:.*Scania.*CN[ ]?=[ ]?([a-zA-Z0-9-_]+).*/$1/
          - RULE:.*CN[ ]?=[ ]?([a-zA-Z0-9-_]+).*\.scania\.com.*/$1/
      loadbalancer:
        enabled: true
        bootstrapPrefix: imtlsonprem #TODO check if this is correct 
        brokerPrefix: imtlsonprem
        internal: true
        name: iris-streaming-sb-imtlsonprem-nlb
        sourceRanges: "13.48.228.240/32, 13.51.76.45/32, 13.51.129.156/32"
    custom:
      internaleks:
        port: 9094
        loadbalancer:
          enabled: false
        authentication:
          type: mtls
          principalMappingRules:
            # First rule may need to be altered to capture Scania-issued client certificates
            - RULE:.*Scania.*CN[ ]?=[ ]?([a-zA-Z0-9-_]+).*/$1/
            - RULE:.*CN[ ]?=[ ]?([a-zA-Z0-9-_]+).*\.scania\.com.*/$1/
      ildaponprem:
        port: 9093
        authentication:
          type: ldap
        loadbalancer:
          enabled: true
          internal: true
          name: iris-streaming-sb-ildaponprem-nlb
          sourceRanges: "13.48.228.240/32, 13.51.76.45/32, 13.51.129.156/32"

controlCenter:
  cfkVersion: 2.5.1
  confluentVersion: 7.3.2
  dataVolumeCapacity: 300Gi
  configOverrides:
    log4j:
      'log4j.appender.stdout': 'org.apache.log4j.ConsoleAppender'
      'log4j.appender.stdout.layout': 'org.apache.log4j.EnhancedPatternLayout'
      'log4j.appender.stdout.layout.ConversionPattern': '{"timestamp":"%d{ISO8601}","level":"%p","thread":"%t","class":"%C","message":"%m%throwable{full}"}%n'
      'log4j.appender.streams.layout.ConversionPattern': '{"timestamp":"%d{ISO8601}","level":"%p","thread":"%t","class":"%C","message":"%m%throwable{full}"}%n'
    server:
      'confluent.controlcenter.mds.client.idle.timeout': '30000'
      'confluent.controlcenter.mds.client.max.requests.queued.per.destination': '2048'
  loadbalancer:
    name:  iris-streaming-sb-icontrolcenter
    nodeLabel: controlcenter
    certificateArn: arn:aws:acm:eu-north-1:572663323550:certificate/a29562a2-f4a3-4c03-b9b5-f77960e0580a
  nodeAffinityServiceName: controlcenter
  dns:
    prefix: icontrolcenter
