apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ca-root
  namespace: confluent
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  target:
    name: ca-root
    creationPolicy: Owner
  data:
    - secretKey: ca.crt
      remoteRef:
        key: {{ .Values.environment }}/{{ .Values.clusterType }}/ca-root
        property: ca.crt
