apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: credential
  namespace: confluent
spec:
  refreshInterval: "1m"  # May be set to zero to fetch and create it once
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  target:
    name: credential
    creationPolicy: Owner
  data:
    - secretKey: plain-users.json
      remoteRef:
        key: {{ .Values.environment }}/{{ .Values.clusterType}}/credential
        property: plain-users.json
    - secretKey: plain.txt
      remoteRef:
        key: {{ .Values.environment }}/{{ .Values.clusterType}}/credential
        property: plain.txt
    - secretKey: digest-users.json
      remoteRef:
        key: {{ .Values.environment }}/{{ .Values.clusterType}}/credential
        property: digest-users.json
    - secretKey: ldap.txt
      remoteRef:
        key: {{ .Values.environment }}/{{ .Values.clusterType}}/credential
        property: ldap.txt
    - secretKey: digest.txt
      remoteRef:
        key: {{ .Values.environment }}/{{ .Values.clusterType}}/credential
        property: digest.txt