apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mds-client
  namespace: confluent
spec:
  refreshInterval: "1m"  # May be set to zero to fetch and create it once
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  target:
    name: mds-client
    creationPolicy: Owner
  data:
    - secretKey: bearer.txt
      remoteRef:
        key: {{ .Values.environment }}/{{ .Values.clusterType}}/mds-client
        property: bearer.txt