apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: restclass-credential
  namespace: confluent
spec:
  refreshInterval: "1m"  # May be set to zero to fetch and create it once
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  target:
    name: restclass-credential
    creationPolicy: Owner
  data:
    - secretKey: basic.txt
      remoteRef:
        key: {{ .Values.environment }}/{{ .Values.clusterType}}/restclass-credential
        property: basic.txt