environment: devtest
clusterType: external

domain:
  name: iris-streaming.devtest.aws.scania.com
  prefix:
    - mtlsaws
    - mtlsonprem
    - oauthaws
    - oauthonprem

externalSecret:
  enabled: true
  aws:
    roleArn: arn:aws:iam::858242954753:role/secrets_manager_dt_ext

ldapProxy:
  enabled: false

datadog:
  enabled: true

filebeat:
  enabled: false #disable file beat 

#kafkalagexporter:
#  enabled: true

certManager:
  enabled: true
clusterIssuer:
  hostedZoneID: Z013025421OH83T6MGYV1

# clusterlinkCustomDashboard:
# #  image: 858242954753.dkr.ecr.eu-north-1.amazonaws.com/clusterlink-topic:3
#   image: 858242954753.dkr.ecr.eu-north-1.amazonaws.com/clusterlink-topic:latest
 
