apiVersion: v2
name: iris-confluent-platform-services
version: 0.0.1
description: Applies Confluent platform CR's for Iris Kubernetes clusters.
keywords:
- Kubernetes
- Confluent
- Kafka
maintainers:
- name: Iris streaming
  email: streaming.ms@scania.com  