defaults:
  confluent:
    #cfkVersion: 2.3.0
    #platformVersion: 7.1.1
    cfkVersion: 2.7.2
    platformVersion: 7.5.2
  ksql:
    configOverrides:
      log4j:
        'log4j.appender.stdout': 'org.apache.log4j.ConsoleAppender'
        'log4j.appender.stdout.layout': 'org.apache.log4j.EnhancedPatternLayout'
        'log4j.appender.stdout.layout.ConversionPattern': '{"timestamp":"%d{ISO8601}","level":"%p","thread":"%t","class":"%C","message":"%m%throwable{full}"}%n'
      server:
        'ksql.streams.num.standby.replicas': 1
        'ksql.query.pull.enable.standby.reads': true
        'ksql.heartbeat.enable': true
        'ksql.lag.reporting.enable': true
        'access.control.allow.origin': '*'
        'access.control.allow.methods': 'GET,POST,HEAD'
        'access.control.allow.headers': 'X-Requested-With,Content-Type,Accept,Origin,Authorization'
kafka:
  annotation:
    'ad.datadoghq.com/kafka.check_names': '["confluent_platform"]'
    'ad.datadoghq.com/kafka.init_configs': '[{"is_jmx": true, "collect_default_metrics": true, "service_check_prefix": "confluent", "new_gc_metrics": true, "collect_default_jvm_metrics": true}]'
    'ad.datadoghq.com/kafka.instances': '[{"host": "%%host%%","port":"7203", "max_returned_metrics":1800}]'
    'ad.datadoghq.com/kafka.logs': '[{"source":"confluent_platform","service":"confluent_platform"}]'
    'secret.reloader.stakater.com/reload': mtls-mapping
    'co.elastic.logs/enabled': "true"     