## Confluent operator name
##
name: confluent-operator
##
## License Key for Operator
##
licenseKey: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjb250cm9sLWNlbnRlciIsIm5iNCI6IjE2MTY2ODYzODYiLCJtb25pdG9yaW5nIjp0cnVlLCJsaWNlbnNlVHlwZSI6IkVudGVycHJpc2UiLCJpc3MiOiJDb25mbHVlbnQiLCJpYXQiOjE2MTcxNzQwMDAsImV4cCI6MTY4MjgzODAwMCwiYXVkIjoiMDA2M2EwMDAwMGl0NDd1QUFBIn0=.uHppd3osXlHvjFF3Q68E8k122WzDm60KcjC6u3VBLkTJcHIqysO8Ilmr6qduuy-4ZveNfzDflcagkSIE9LQhmH6R_hJsEpU8Dnaql4beRG3SmV_d-h990jZzgD468n6K2f-Tokj4XE4qfra2x1wGQX6aAm2EZhEDzC6dyugD1DwZmpKXwHmp-rU0nsp7cPaGWffEzRsl-jznRNjZxyfHS7gRQMl1L9XXbTQWA2Sd3QUVUovstj5huDgHuGyDh_1ilc6uG3ThUASgJgvqMuIwx2i4Rc-C3s2q1sq5aOejsArF017uMXVWD1gXJ4VJgE4JNCerDBOe4pI9ie9YYw86yw"
publicKey: |-
  -----BEGIN PUBLIC KEY-----
  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvaGy8TOdbCMySM7zqZsx
  n62yuE+BhIPlc9z9ctrX+tBWNCCJePZbKHTZS9uKLeKUi9u07ts/35XRnE4ATD6q
  lwjnSoJOkeIXcYiJ+XGExN1oRE8Rl5otvdmJEsb9Y6Jsfe2lRCCsZNx6k1s1NmQF
  R4wnRiKylIiYJ9uWUGfH18JKZqM8z9QqkZ/+zQkzHNYsXn/YyRuDIQXeUSechr93
  Jjt79AikskicoT04lqz/GaHz2WJEyuvLLE1jNBOComKl05Qb+yvJmGnt/7HX6HT7
  3hnCXbslwtzp0CmeGOiJRbJxbahkTFqh1oKqZXUDCZrKCNNRvXqN/QHqnawo6kJy
  8wIDAQAB
  -----END PUBLIC KEY-----
##
## The license secret ref is injected through
## CONFLUENT_LICENSE_SECRET_NAME environment variable.
## The expected keys: license.txt, publicKey.pem
## If the value is empty, then charts will create license secret
## with name `confluent-operator-licensing`
###
licenseSecretRef: ""
###
## Image pull secret
imagePullSecretRef:  confluent-registry
## Confluent Operator Image Information
##
image:
  registry: docker.io
  repository: confluentinc/confluent-operator
  pullPolicy: IfNotPresent
  tag: "0.435.11"

###
## Priority class for Confluent Operator pod
priorityClassName: ""
## Number of pods for Operator
## Enables leader election if more than one replica
replicas: 1
## Confluent Operator Cluster Access
## If true, operator only creates roles/rolebinding for the release namespace
## Otherwise, it has cluster access with clusterrole/clusterrrolebinding
namespaced: true
### list of namespaces to watch by operator
### This field only takes in effect if `namespaced=true`. By default, it will only watch the release namespace
### Otherwise, it will watch specified namespaces. If watching only release namespace, do not specify this field
namespaceList: []
## Confluent Operator Pod Resources
##
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
## Pod termination grace-period
##
terminationGracePeriodSeconds: 30
## Enable debugging
##
debug: false
##
## Configure affinity,
## More information here https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
##
affinity: {}
##  Example for nodeAffinity, configure as required.
##affinity:
##  nodeAffinity:
##    requiredDuringSchedulingIgnoredDuringExecution:
##      nodeSelectorTerms:
##      - matchExpressions:
##        - key: "node-role.kubernetes.io/compute"
##          operator: In
##          values:
##          - "true"

##
## Configure tolerations
## https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []
##
##tolerations:
##- key: "dedicated"
##  operator: "Equal"
##  value: "operator"
##  effect: "NoSchedule"

## Pod Security Context
##
podSecurity:
  enabled: true
  securityContext:
    fsGroup: 1001
    runAsUser: 1001
    runAsNonRoot: true
##
## ServiceAccount
## If enabled it will create, otherwise it will
## not create
##
serviceAccount:
  create: true
  name: ""
## Enable Kubernetes RBAC
## When set to true, it will create a proper role/rolebinding or cluster/clusterrolebinding based on namespaced field.
## If a user doesn't have permission to create role/rolebinding then they can disable rbac field and
## create required resources out of band to be used by the Operator. In this case, follow the
## templates/clusterrole.yaml and templates/clusterrolebiding.yaml to create proper required resources.
rbac: true

## Enable extra Kubernetes API groups in role/clusterrole resource
## When set to true, it will add apiGroups to role/clusterrole for Operator 1.x Migration and OpenShift route resource
clusterRole:
  migration: true
  openshift: true

###
### Confluent Telemetry Report configuration
## The secretRef contains following data,
## telemetry.txt: |-
##   api.key=<api_key>
##   api.secret=<api_secret>
##   proxy.url=<proxy_url>  # only required if proxy is enabled
##   proxy.username=<proxy_username> # only required if proxy requires credential
##   proxy.password=<proxy_password>
##
telemetry:
  enabled: false
  proxy:
    enabled: false
    credentialRequired: false
  secretRef: ""
  ## To use directoryPathInContainer, need to make sure
  ## you mount telemetry.txt in the path you provided here in each pod
  directoryPathInContainer: ""

##
## Pod annotations/labels configurations
##
pod:
  annotations:
    prometheus.io/path: "/metrics"
    prometheus.io/port: "7778"
    prometheus.io/scrape: "true"
  labels: {}
# labels:
#   key: "value"
