fullnameOverride: external-dns

provider: aws
aws:
  zoneType: public
  region: eu-north-1

policy: upsert-only
registry: txt
txtOwnerId: external-dns
txtSuffix: "_externaldns"
serviceAccount:
  annotations: 
    eks.amazonaws.com/role-arn: arn:aws:iam::541662535189:role/external-dns-irsa-role-ext

sources:
  - service
  - ingress
domainFilters:
  - 'iris-streaming.prod.aws.scania.com'
