apiVersion: v2
name: iris-cluster-tools
version: 0.0.1
description: Installs External-DNS, Ldap-proxy, Filebeat etc. to Kubernetes clusters. 
keywords:
- External-dns
- Confluent
- Kafka
maintainers:
- name: Iris streaming
  email: streaming.ms@scania.com  
  