{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kafka-tls
  namespace: confluent
spec:
  secretName: kafka-tls
  dnsNames:
  - '*.kafka.{{ .Values.domain.name }}'
  {{- range .Values.domain.prefix }}
  - '*.{{ . }}.kafka.{{ $.Values.domain.name }}'
  {{- end }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
    group: cert-manager.io
{{- end }}