{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: confluent
spec:
  secretName: wildcard-cert
  dnsNames:
  - '*.{{ .Values.domain.name }}'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
    group: cert-manager.io
{{- end }}