{{ if .Values.externalSecret.enabled}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-service
  namespace: external-secrets
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.externalSecret.aws.roleArn }}
{{- end }}