--- 
apiVersion: v1
kind: Service
metadata:
  namespace: confluent
  annotations: 
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/load-balancer-name: rp-onprem-iris-streaming-sb-devtest-onpremconnect-alb
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/subnets: subnet-005c0a53190a785d7, subnet-000ec77e207799a57, subnet-0700aa03c92c90b8a
    alb.ingress.kubernetes.io/inbound-cidrs: 13.48.228.240/32, 13.51.76.45/32, 13.51.129.156/32
    external-dns.alpha.kubernetes.io/hostname: onpremrp.iris-streaming-sb.devtest.aws.scania.com
  name: restproxy-onprem-bootstrap-lb
spec: 
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports: 
    - 
      name: external
      port: 443
      protocol: TCP
      targetPort: 8085
  selector: 
    app: KafkaRestProxy
    clusterId: confluent
    confluent-platform: "true"
    type: KafkaRestProxy
  sessionAffinity: None
  type: LoadBalancer


