apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestProxy
metadata:
  name: kafkarestproxy
  namespace: confluent
spec:
#  authentication:
#    basic:
#      secretRef: kafkarestproxy-users
#    type: basic
  authentication:
    type: mtls
  tls:
    secretRef: tls-group
  authorization:
    type: rbac
  dependencies:
    kafka:
      bootstrapEndpoint:  kafka.confluent.svc.cluster.local:9071
      authentication:
        type: plain
        jaasConfig:
          secretRef: credential
      tls:
        enabled: true
    mds:
      #endpoint: https://mds.iris-streaming-sb.devtest.aws.scania.com:443
      endpoint: https://mds-cc-sbox.iris-streaming-sb.devtest.aws.scania.com:443
      tokenKeyPair:
        secretRef: mds-token
      authentication:
        type: bearer
        bearer:
        #we are using internal user kafka for rest proxy
        #to do: change it to rp-mds-client
          secretRef: mds-client 
      tls:
        enabled: true
    schemaRegistry:
      # authentication:
      #   basic:
      #     secretRef: credential
      #   type: basic
      tls:
        enabled: true
      url: https://schemaregistry.operator.svc.cluster.local:8081
  image:
    application: confluentinc/cp-kafka-rest:7.1.1
    init: confluentinc/confluent-init-container:2.3.0
#    pullSecretRef:
#      - confluent-registry
  replicas: 1
#  tls:
#    autoGeneratedCerts: true
  externalAccess:
    type: loadBalancer
    loadBalancer:
       annotations:
         kubernetes.io/ingress.class: alb
         alb.ingress.kubernetes.io/scheme: internet-facing
         alb.ingress.kubernetes.io/load-balancer-name: iris-streaming-sb-restproxy-alb
         alb.ingress.kubernetes.io/target-type: instance
         alb.ingress.kubernetes.io/subnets: subnet-05f7a5ed2f3bffe1f, subnet-01134504e0e2585cb, subnet-0b0d0d44264a719c2
         alb.ingress.kubernetes.io/inbound-cidrs: 13.48.228.240/32, 13.51.76.45/32, 13.51.129.156/32
         external-dns.alpha.kubernetes.io/hostname: restproxy.iris-streaming-sb.devtest.aws.scania.com
       domain: iris-streaming-sb.devtest.aws.scania.com
       #prefix: restproxy
       prefix: restproxy-sbox
#    oneReplicaPerNode: true
  podTemplate:
    podSecurityContext:
      fsGroup: 1000
      runAsGroup: 1000
      runAsUser: 1000
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: service
                  operator: In
                  values:
                    - srrp
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - kafka
                    - zookeeper
            topologyKey: kubernetes.io/hostname
