##
## License Key for Operator
## TODO: use license.secretref to populate from license secret instead.
licenseKey: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjb250cm9sLWNlbnRlciIsIm5iNCI6IjE2ODA3Mzk0MDYiLCJtb25pdG9yaW5nIjp0cnVlLCJsaWNlbnNlVHlwZSI6IkVudGVycHJpc2UiLCJpc3MiOiJDb25mbHVlbnQiLCJpYXQiOjE2ODAyNDYwMDAsImV4cCI6MTcxNDQ2MDQwMCwiYXVkIjoiMDA2M2EwMDAwMGlmeEtoQUFJIn0=.rl_POa8HJh1FcHU8b1Q9FFYYvgxafwQqO4mVXqnb1j7pfCHEj2iJGAd6mhUK-YjjRbWfGfcycOCVkqm4vV51uK9qfgbrcwC38PIOoqM_BKQwGhQOybT16xt16baPfj2c5Lm4YLOQHM9IZySV6W4hH8YTjn90LmsHHZBy4e3T2XwW6f5bJjnTstXECVZL3Q6hUi4oOMUnVxHOXh4kbh2rb4WCfFS9JCOzhlIMIH5-RSTJMSI_AcffXG9cLRdyww3JNFPRwUNMMwHlGjwCjrybHDIjnuTtB4P2rOcHZd6n1d2eWi-kYobVfZVKBgw5LGY03zsQnkjgcWLF3O-HbeWdBQ"

replicas: 1

clusterRole:
  openshift: false