{{- if .Values.storageClass.enabled }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
  labels:
    {{- include "kafka-eks.labels" . | nindent 4 }}
provisioner: {{ .Values.storageClass.provisioner }}
parameters:
  type: {{ .Values.storageClass.type }}
  {{- if .Values.storageClass.encrypted }}
  encrypted: "true"
  {{- end }}
  {{- if .Values.storageClass.kmsKeyId }}
  kmsKeyId: {{ .Values.storageClass.kmsKeyId }}
  {{- end }}
  {{- if .Values.storageClass.iops }}
  iops: {{ .Values.storageClass.iops | quote }}
  {{- end }}
  {{- if .Values.storageClass.throughput }}
  throughput: {{ .Values.storageClass.throughput | quote }}
  {{- end }}
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode | default "WaitForFirstConsumer" }}
allowVolumeExpansion: {{ .Values.storageClass.allowVolumeExpansion | default true }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy | default "Retain" }}
{{- end }}
