apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect
  namespace: confluent
spec:
  replicas: 2
  oneReplicaPerNode: true
  image:
    application: confluentinc/cp-server-connect:7.0.1
    init: confluentinc/confluent-init-container:2.2.0-1
  build:
    type: onDemand
    onDemand:
      plugins:
        locationType: confluentHub                          #if the k8s have internet connection i.e to confluenthub
        confluentHub:
          - name: kafka-connect-datagen
            owner: confluentinc
            version: 0.5.2
          - name: debezium-connector-mysql
            owner: debezium
            version: 1.7.1
          - name: kafka-connect-hdfs3
            owner: confluentinc
            version: 1.1.8
  dependencies:
    kafka:
      bootstrapEndpoint: kafka:9071
  configOverrides:
    server:
      - key.converter=org.apache.kafka.connect.storage.StringConverter
      - value.converter=io.confluent.connect.avro.AvroConverter
      - value.converter.schema.registry.url=http://schemaregistry:8081

  externalAccess:
#    type: nodePort
#    nodePort:
#      host: connect.iris-streaming-sb.devtest.aws.scania.com
#      nodePortOffset: 30300
    type: loadBalancer
    loadBalancer:
      annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/load-balancer-name: iris-streaming-sb-connect-alb
        alb.ingress.kubernetes.io/target-type: instance
        alb.ingress.kubernetes.io/subnets: subnet-03bb1df2bc15436b6, subnet-061b406bbac050fcb, subnet-0a71781428bea6c6e
        alb.ingress.kubernetes.io/inbound-cidrs: 13.51.132.182/32, 13.51.115.193/32, 13.51.138.3/32
        external-dns.alpha.kubernetes.io/hostname: connect.iris-streaming-sb.devtest.aws.scania.com
      domain: iris-streaming-sb.devtest.aws.scania.com
      prefix: connect
#  storageClass:
#    name: standard
  podTemplate:
    podSecurityContext:
      fsGroup: 1000
      runAsGroup: 1000
      runAsUser: 1000
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: service
                  operator: In
                  values:
                    - connect
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: service
                  operator: In
                  values:
                    - kafka0
            topologyKey: kubernetes.io/hostname
