##
## License Key for Operator
## TODO: use license.secretref to populate from license secret instead.
licenseKey: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjb250cm9sLWNlbnRlciIsIm5iNCI6IjE2MTY2ODYzODYiLCJtb25pdG9yaW5nIjp0cnVlLCJsaWNlbnNlVHlwZSI6IkVudGVycHJpc2UiLCJpc3MiOiJDb25mbHVlbnQiLCJpYXQiOjE2MTcxNzQwMDAsImV4cCI6MTY4MjgzODAwMCwiYXVkIjoiMDA2M2EwMDAwMGl0NDd1QUFBIn0=.uHppd3osXlHvjFF3Q68E8k122WzDm60KcjC6u3VBLkTJcHIqysO8Ilmr6qduuy-4ZveNfzDflcagkSIE9LQhmH6R_hJsEpU8Dnaql4beRG3SmV_d-h990jZzgD468n6K2f-Tokj4XE4qfra2x1wGQX6aAm2EZhEDzC6dyugD1DwZmpKXwHmp-rU0nsp7cPaGWffEzRsl-jznRNjZxyfHS7gRQMl1L9XXbTQWA2Sd3QUVUovstj5huDgHuGyDh_1ilc6uG3ThUASgJgvqMuIwx2i4Rc-C3s2q1sq5aOejsArF017uMXVWD1gXJ4VJgE4JNCerDBOe4pI9ie9YYw86yw"

replicas: 1

clusterRole:
  openshift: false