{{ if .Values.datadog.enabled}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datadog-api-key
  namespace: datadog
spec:
  refreshInterval: "1m"  # May be set to zero to fetch and create it once
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  target:
    name: datadog
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: {{ .Values.environment }}/datadog
        property: api-key
{{- end }}
