environment: prod
clusterType: external

externalSecret:
  enabled: true
  aws:
    roleArn: arn:aws:iam::541662535189:role/secrets_manager_prod_ext 

ldapProxy:
  enabled: false

datadogAgent:
  enabled: false

filebeat:
  enabled: true