environment: prod
clusterType: internal

externalSecret:
  enabled: true
  aws:
    roleArn: arn:aws:iam::541662535189:role/secrets_manager_prod_role

ldapProxy:
  enabled: false

datadog:
  enabled: true

filebeat:
  enabled: true