environment: prod
clusterType: external

domain:
  name: iris-streaming.prod.aws.scania.com
  prefix:
    - mtlsaws
    - mtlsonprem
    - oauthaws
    - oauthonprem

externalSecret:
  enabled: true
  aws:
    roleArn: arn:aws:iam::541662535189:role/secrets_manager_prod_ext 

ldapProxy:
  enabled: true

datadog:
  enabled: true

filebeat:
  enabled: true

kafkalagexporter:
  enabled: true

certManager:
  enabled: false
clusterIssuer:
  hostedZoneID: Z0523917343SHVNQKTNUD
