environment: prod
clusterType: internal

domain:
  name: iris-streaming.prod.aws.scania.com
  prefix:
    - imtlsaws
    - imtlsonprem
    - ioauthaws
    - ioauthonprem

externalSecret:
  enabled: true
  aws:
    roleArn: arn:aws:iam::541662535189:role/secrets_manager_prod_role

ldapProxy:
  enabled: true

datadog:
  enabled: true

filebeat:
  enabled: true

kafkalagexporter:
  enabled: true

certManager:
  enabled: false
clusterIssuer:
  hostedZoneID: Z0523917343SHVNQKTNUD
