#{{ if (.Values.kafkalagexporter).enabled}}
#apiVersion: external-secrets.io/v1beta1
#kind: ExternalSecret
#metadata:
#  name: kafka-ca
#  namespace: kafka-lag-exporter
#spec:
#  refreshInterval: "1m"  # May be set to zero to fetch and create it once
#  secretStoreRef:
#    name: global-secret-store
#    kind: ClusterSecretStore
#  target:
#    name: kafka-ca
#    creationPolicy: Owner
#  data:
#    - secretKey: ca.crt
#      remoteRef:
#        key: {{ .Values.environment }}/{{ .Values.clusterType }}/tls-group
#        property: cacerts.pem
#---
#apiVersion: external-secrets.io/v1beta1
#kind: ExternalSecret
#metadata:
#  name: kafka-credentials
#  namespace: kafka-lag-exporter
#spec:
#  refreshInterval: "1m"  # May be set to zero to fetch and create it once
#  secretStoreRef:
#    name: global-secret-store
#    kind: ClusterSecretStore
#  target:
#    name: kafka-credentials
#    creationPolicy: Owner
#  data:
#    - secretKey: KAFKA_USERNAME
#      remoteRef:
#        key: {{ .Values.environment }}/{{ .Values.clusterType }}/kafka-lag-exporter-credentials
#        property: username
#    - secretKey: KAFKA_PASSWORD
#      remoteRef:
#        key: {{ .Values.environment }}/{{ .Values.clusterType }}/kafka-lag-exporter-credentials
#        property: password
#{{- end }}
